In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
pd.options.display.max_rows = 100
pd.options.display.min_rows = 20
pd.options.display.max_columns = None

In [3]:
ROOT_PATH = Path(Path.cwd()).resolve().parent
DATA_PATH = ROOT_PATH/'data'/'raw'/'dbasket'/'csv'
PROCESSED_PATH = ROOT_PATH/'data'/'processed'

# Creación de DataFrame principal

In [4]:
dfs = []

for file in Path(DATA_PATH).glob('*.csv'):
    jornada = int(file.stem.split('_')[-1])
    df_temp = pd.read_csv(file)
    df_temp['Jornada'] = jornada
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)
df = df.sort_values(by=['#', 'Jornada']).reset_index(drop=True)

# Modificaciones a DF

## Eliminar datos totales y de equipo

In [5]:
df.dropna(subset=['#'], inplace=True)

## Cambio de nombre de columnas

In [6]:
df = df.rename(columns= {'#ERROR!': '+/-'})

## Estandarización de datos

In [7]:
cambio_dtype = {
    '#': 'int64',
    'TCA': 'int64',
    'TCI': 'int64',
    'T3A': 'int64',
    'T3I': 'int64',
    'TLA': 'int64',
    'TLI': 'int64',
    'ASI': 'int64',
    'ROB': 'int64',
    'TAP': 'int64',
    'TAPR': 'int64',
    'FPR': 'int64',
    'PTS': 'int64'
}
df = df.astype(cambio_dtype)

In [8]:
# df['%TC'] = (df['TCA'] / df['TCI'] * 100).round(2).fillna(0)
# df['%TL'] = (df['TLA'] / df['TLI'] * 100).round(2).fillna(0)
# df['%T3'] = (df['T3A'] / df['T3I'] * 100).round(2).fillna(0)

## Creación de nuevas variables

In [9]:
# Lista de adversarios
adv_dict = {
    1: 'MoraBanc Andorra',
    2: 'Basquet Girona',
    3: 'La Laguna Tenerife',
    4: 'Baskonia',
    5: 'FC Barcelona',
    6: 'BAXI Manresa',
    7: 'Río Breogán',
    8: 'Hiopos Lleida',
    9: 'Recoletas Salud San Pablo Burgos',
    10: 'Joventut Badalona',
    11: 'Valencia Basket',
    12: 'Covirán Granada',
    13: 'Real Madrid',
    14: 'Dreamland Gran Canaria',
    15: 'Surne Bilbao Basket',
    16: 'Basket Zaragoza',
    17: 'Unicaja Málaga',
    18: 'FC Barcelona',
    19: 'Río Breogán',
    20: 'Recoletas Salud San Pablo Burgos',
    21: 'Valencia Basket',
    22: 'Dreamland Gran Canaria',
    23: 'BAXI Manresa',
    24: 'Surne Bilbao Basket',
    25: 'Joventut Badalona',
    26: 'Covirán Granada',
    27: 'MoraBanc Andorra',
    28: 'La Laguna Tenerife',
    29: 'Real Madrid',
    30: 'Bàsquet Girona',
    31: 'Baskonia',
    32: 'Unicaja Málaga',
    33: 'Casademont Zaragoza',
    34: 'Hiopos Lleida'
}

# Local o Visitante
partido_local = {
    1: 'Local',
    2: 'Visitante',
    3: 'Visitante',
    4: 'Local',
    5: 'Visitante',
    6: 'Local',
    7: 'Local',
    8: 'Visitante',
    9: 'Visitante',
    10: 'Local',
    11: 'Local',
    12: 'Visitante',
    13: 'Local',
    14: 'Visitante',
    15: 'Visitante',
    16: 'Local',
    17: 'Visitante',
    18: 'Local',
    19: 'Visitante',
    20: 'Local',
    21: 'Visitante',
    22: 'Local',
    23: 'Visitante',
    24: 'Local',
    25: 'Visitante',
    26: 'Local',
    27: 'Visitante',
    28: 'Local',
    29: 'Visitante',
    30: 'Local',
    31: 'Visitante',
    32: 'Local',
    33: 'Visitante',
    34: 'Local'
}

# Vuelta
vuelta = {
    1: '1ª Vuelta',
    2: '1ª Vuelta',
    3: '1ª Vuelta',
    4: '1ª Vuelta',
    5: '1ª Vuelta',
    6: '1ª Vuelta',
    7: '1ª Vuelta',
    8: '1ª Vuelta',
    9: '1ª Vuelta',
    10: '1ª Vuelta',
    11: '1ª Vuelta',
    12: '1ª Vuelta',
    13: '1ª Vuelta',
    14: '1ª Vuelta',
    15: '1ª Vuelta',
    16: '1ª Vuelta',
    17: '1ª Vuelta',
    18: '2ª Vuelta',
    19: '2ª Vuelta',
    20: '2ª Vuelta',
    21: '2ª Vuelta',
    22: '2ª Vuelta',
    23: '2ª Vuelta',
    24: '2ª Vuelta',
    25: '2ª Vuelta',
    26: '2ª Vuelta',
    27: '2ª Vuelta',
    28: '2ª Vuelta',
    29: '2ª Vuelta',
    30: '2ª Vuelta',
    31: '2ª Vuelta',
    32: '2ª Vuelta',
    33: '2ª Vuelta',
    34: '2ª Vuelta'
}

In [10]:
df['Adversario'] = df['Jornada'].map(adv_dict)
df['Local'] = df['Jornada'].map(partido_local)
df['Vuelta'] = df['Jornada'].map(vuelta)

In [13]:
df

,#,Jugador,MIN,TCA,TCI,%TC,T3A,T3I,%T3,TLA,TLI,%TL,RO,RD,REB,ASI,PER,ROB,TAP,TAPR,FP,FPR,PTS,+/-,VAL,Jornada,Adversario,Local,Vuelta
0,0,Devontae Cacok,16:41,3,6,50,0,0,0,2,2,100,3,5,8,1,1,2,0,0,3,2,8,8.0,14,1,MoraBanc Andorra,Local,1ª Vuelta
1,0,Devontae Cacok,21:43,3,6,50,0,0,0,5,6,"83,33",3,4,7,0,1,0,0,0,4,7,11,25.0,16,2,Basquet Girona,Visitante,1ª Vuelta
2,0,Devontae Cacok,20:46,3,3,100,0,0,0,4,4,100,1,2,3,1,3,1,0,0,3,2,10,-1.0,11,3,La Laguna Tenerife,Visitante,1ª Vuelta
3,0,Devontae Cacok,13:35,2,2,100,0,0,0,0,0,0,0,0,0,1,2,0,0,0,4,1,4,-9.0,0,4,Baskonia,Local,1ª Vuelta
4,0,Devontae Cacok,21:22,9,10,90,0,0,0.0,2,3,"66,67",2,4,6,0,4,1,0,1,5,5,20,3.0,21,5,FC Barcelona,Visitante,1ª Vuelta
5,0,Devontae Cacok,10:56,2,4,50,0,0,0,1,2,50.0,2,2,4,0,1,0,0,0,2,4,5,-5.0,7,6,BAXI Manresa,Local,1ª Vuelta
6,0,Devontae Cacok,12:52,1,3,"33,33",0,0,0,0,0,0,3,0,3,0,1,1,0,1,2,4,2,-6.0,5,7,Río Breogán,Local,1ª Vuelta
7,0,Devontae Cacok,12:21,3,4,75,0,0,0,1,4,25,1,2,3,2,1,0,1,0,3,3,7,19.0,8,8,Hiopos Lleida,Visitante,1ª Vuelta
8,0,Devontae Cacok,21:26,9,11,"81,82",0,0,0,1,4,25,2,6,8,3,1,1,0,0,3,3,19,29.0,25,9,Recoletas Salud San Pablo Burgos,Visitante,1ª Vuelta
9,0,Devontae Cacok,21:07,3,6,50,0,0,0,3,5,60,0,3,3,0,2,2,1,0,4,4,9,8.0,8,11,Valencia Basket,Local,1ª Vuelta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,99,Toni Nakic,16:04,2,4,50,2,4,50,2,2,100,1,2,3,0,0,0,1,0,0,0,8,-16.0,10,12,Covirán Granada,Visitante,1ª Vuelta
227,99,Toni Nakic,10:02,0,4,0,0,3,0,0,0,0,0,2,2,0,0,0,0,0,3,0,0,-2.0,-5,13,Real Madrid,Local,1ª Vuelta
228,99,Toni Nakic,16:33,2,6,"33,33",1,5,20,0,0,0,1,1,2,0,1,0,0,0,2,0,5,-2.0,0,14,Dreamland Gran Canaria,Visitante,1ª Vuelta
229,99,Toni Nakic,18:13,0,2,0,0,2,0,0,0,0,0,0,0,1,1,1,0,0,2,1,0,-4.0,-2,15,Surne Bilbao Basket,Visitante,1ª Vuelta
230,99,Toni Nakic,17:24,3,6,50,3,5,60,2,2,100,1,2,3,0,0,0,0,0,2,3,11,-4.0,12,16,Basket Zaragoza,Local,1ª Vuelta
231,99,Toni Nakic,32:10:00,3,6,50,3,6,50,1,1,100,0,1,1,0,0,1,0,0,1,2,10,-2.0,10,17,Unicaja Málaga,Visitante,1ª Vuelta
232,99,Toni Nakic,32:10:00,3,6,50,3,6,50,1,1,100,0,1,1,0,0,1,0,0,1,2,10,-2.0,10,18,FC Barcelona,Local,2ª Vuelta
233,99,Toni Nakic,26:10:00,2,6,"33,33",1,5,20,0,0,0,1,2,3,2,0,3,1,0,2,4,5,11.0,12,19,Río Breogán,Visitante,2ª Vuelta
234,99,Toni Nakic,12:51,2,2,100,1,1,100,0,0,0,0,2,2,0,1,2,0,0,0,1,5,6.0,9,20,Recoletas Salud San Pablo Burgos,Local,2ª Vuelta
235,99,Toni Nakic,18:59,0,5,0,0,2,0,0,0,0,1,1,2,2,0,0,0,1,1,0,0,-28.0,-2,21,Valencia Basket,Visitante,2ª Vuelta

In [57]:
# Se cambia la información del tiempo jugado a segundos en SEG y se elimina MIN
df['SEG'] = (
    df['MIN']
    .str.split(':')
    .apply(lambda x: int(x[0]) * 60 + int(x[1]))
)

In [58]:
df['#'] = df['#'].astype(str).str.zfill(2)

## Se eliminan columnas inservibles

In [59]:
df.drop(columns=['MIN', '%TC', '%T3', '%TL'], inplace=True)

## Se corrigen datos

In [60]:
display(df)

,#,Jugador,TCA,TCI,T3A,T3I,TLA,TLI,RO,RD,REB,ASI,PER,ROB,TAP,TAPR,FP,FPR,PTS,+/-,VAL,Jornada,Adversario,Local,Vuelta,SEG
0,00,Devontae Cacok,3,6,0,0,2,2,3,5,8,1,1,2,0,0,3,2,8,8.0,14,1,MoraBanc Andorra,Local,1ª Vuelta,1001
1,00,Devontae Cacok,3,6,0,0,5,6,3,4,7,0,1,0,0,0,4,7,11,25.0,16,2,Basquet Girona,Visitante,1ª Vuelta,1303
2,00,Devontae Cacok,3,3,0,0,4,4,1,2,3,1,3,1,0,0,3,2,10,-1.0,11,3,La Laguna Tenerife,Visitante,1ª Vuelta,1246
3,00,Devontae Cacok,2,2,0,0,0,0,0,0,0,1,2,0,0,0,4,1,4,-9.0,0,4,Baskonia,Local,1ª Vuelta,815
4,00,Devontae Cacok,9,10,0,0,2,3,2,4,6,0,4,1,0,1,5,5,20,3.0,21,5,FC Barcelona,Visitante,1ª Vuelta,1282
5,00,Devontae Cacok,2,4,0,0,1,2,2,2,4,0,1,0,0,0,2,4,5,-5.0,7,6,BAXI Manresa,Local,1ª Vuelta,656
6,00,Devontae Cacok,1,3,0,0,0,0,3,0,3,0,1,1,0,1,2,4,2,-6.0,5,7,Río Breogán,Local,1ª Vuelta,772
7,00,Devontae Cacok,3,4,0,0,1,4,1,2,3,2,1,0,1,0,3,3,7,19.0,8,8,Hiopos Lleida,Visitante,1ª Vuelta,741
8,00,Devontae Cacok,9,11,0,0,1,4,2,6,8,3,1,1,0,0,3,3,19,29.0,25,9,Recoletas Salud San Pablo Burgos,Visitante,1ª Vuelta,1286
9,00,Devontae Cacok,3,6,0,0,3,5,0,3,3,0,2,2,1,0,4,4,9,8.0,8,11,Valencia Basket,Local,1ª Vuelta,1267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,99,Toni Nakic,2,4,2,4,2,2,1,2,3,0,0,0,1,0,0,0,8,-16.0,10,12,Covirán Granada,Visitante,1ª Vuelta,964
227,99,Toni Nakic,0,4,0,3,0,0,0,2,2,0,0,0,0,0,3,0,0,-2.0,-5,13,Real Madrid,Local,1ª Vuelta,602
228,99,Toni Nakic,2,6,1,5,0,0,1,1,2,0,1,0,0,0,2,0,5,-2.0,0,14,Dreamland Gran Canaria,Visitante,1ª Vuelta,993
229,99,Toni Nakic,0,2,0,2,0,0,0,0,0,1,1,1,0,0,2,1,0,-4.0,-2,15,Surne Bilbao Basket,Visitante,1ª Vuelta,1093
230,99,Toni Nakic,3,6,3,5,2,2,1,2,3,0,0,0,0,0,2,3,11,-4.0,12,16,Basket Zaragoza,Local,1ª Vuelta,1044
231,99,Toni Nakic,3,6,3,6,1,1,0,1,1,0,0,1,0,0,1,2,10,-2.0,10,17,Unicaja Málaga,Visitante,1ª Vuelta,1930
232,99,Toni Nakic,3,6,3,6,1,1,0,1,1,0,0,1,0,0,1,2,10,-2.0,10,18,FC Barcelona,Local,2ª Vuelta,1930
233,99,Toni Nakic,2,6,1,5,0,0,1,2,3,2,0,3,1,0,2,4,5,11.0,12,19,Río Breogán,Visitante,2ª Vuelta,1570
234,99,Toni Nakic,2,2,1,1,0,0,0,2,2,0,1,2,0,0,0,1,5,6.0,9,20,Recoletas Salud San Pablo Burgos,Local,2ª Vuelta,771
235,99,Toni Nakic,0,5,0,2,0,0,1,1,2,2,0,0,0,1,1,0,0,-28.0,-2,21,Valencia Basket,Visitante,2ª Vuelta,1139

# Export

In [61]:
df.to_csv(
    PROCESSED_PATH/'Datos_dbasket.csv',
    sep=';',
    decimal=',',
    index=False
)